# Generated by Django 3.2.14 on 2022-11-04 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('email', models.CharField(help_text='Mail for sending messages', max_length=150, null=True, verbose_name='E-mail address')),
            ],
            options={
                'verbose_name': 'Sender',
                'verbose_name_plural': 'Senders',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=150, null=True, verbose_name='Template')),
                ('topic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Topic')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Identifier')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.mailsender')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SendingMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_everyone', models.BooleanField(default=False, verbose_name='Send to everyone')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('emails', models.ManyToManyField(blank=True, to='contact.Subscription')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.mailtemplate')),
            ],
            options={
                'verbose_name': 'Sending mail',
                'verbose_name_plural': 'Sending mails',
                'ordering': ['date'],
            },
        ),
    ]
