# Generated by Django 3.2.14 on 2022-10-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmail', '0016_auto_20221001_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='SendingMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_everyone', models.BooleanField(default=False)),
                ('use_celery', models.BooleanField(default=False)),
                ('emails', models.ManyToManyField(blank=True, to='contact.Subscription')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmail.mailtemplate')),
            ],
            options={
                'verbose_name': 'Отправка сообщения',
                'verbose_name_plural': 'Отправка сообщений',
            },
        ),
    ]
