# Generated by Django 3.2.14 on 2022-10-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220809_1609'),
        ('users', '0004_alter_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
