# Generated by Django 3.2.14 on 2022-08-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
    ]
